// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmay4gY50jCKos8ZtgiydA4AyIOrhgB44',
    appId: '1:35180494234:web:b39a64970bcb5d9107ce23',
    messagingSenderId: '35180494234',
    projectId: 'flutter-inquiry-form',
    authDomain: 'flutter-inquiry-form.firebaseapp.com',
    storageBucket: 'flutter-inquiry-form.firebasestorage.app',
    measurementId: 'G-5Y4BG7YJLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChIRcwm46Zbg-y3vGd9-NZY10Y7cxKK6s',
    appId: '1:35180494234:android:e11487d6e6e2391307ce23',
    messagingSenderId: '35180494234',
    projectId: 'flutter-inquiry-form',
    storageBucket: 'flutter-inquiry-form.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDiObG-4weSrJv1UAER8bb2TbvUbj-P5Y',
    appId: '1:35180494234:ios:95a80eed8a3f9e9307ce23',
    messagingSenderId: '35180494234',
    projectId: 'flutter-inquiry-form',
    storageBucket: 'flutter-inquiry-form.firebasestorage.app',
    iosBundleId: 'com.example.reusableButtonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDiObG-4weSrJv1UAER8bb2TbvUbj-P5Y',
    appId: '1:35180494234:ios:95a80eed8a3f9e9307ce23',
    messagingSenderId: '35180494234',
    projectId: 'flutter-inquiry-form',
    storageBucket: 'flutter-inquiry-form.firebasestorage.app',
    iosBundleId: 'com.example.reusableButtonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmay4gY50jCKos8ZtgiydA4AyIOrhgB44',
    appId: '1:35180494234:web:ee00ddd46b3a11ef07ce23',
    messagingSenderId: '35180494234',
    projectId: 'flutter-inquiry-form',
    authDomain: 'flutter-inquiry-form.firebaseapp.com',
    storageBucket: 'flutter-inquiry-form.firebasestorage.app',
    measurementId: 'G-62MXPQSGV9',
  );
}
